apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logging-0
  labels:
    name: efk
spec:
  storageClassName: efk
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/es/0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logging-1
  labels:
    name: efk
spec:
  storageClassName: efk
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/es/1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-logging-2
  labels:
    name: efk
spec:
  storageClassName: efk
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/es/2
